### ISSUE TITLE
実際には本割り当てされたピアIDが使用されていない

### ISSUE THREAD

**Issue by ingen084** [p2pquake/epsp-specifications#10]
仕様書通りEPSPを一通り実装させていただいたのですがエコー･ネットワークからの離脱が `299` で失敗するため、公式のP2P地震情報クライアントの通信内容を解析させていただきました。
そのところ、本割り当てを要求しているにも関わらず、仮割り当てされたピアIDがずっと使用されていました。

現状の状況の追記などお願いできませんでしょうか？

**Comment by typewriter** [comment]
@ingen084 大変遅くなりました。
コード `236` （ピアIDの本割り当て） の返却データは `現在の参加ピア総数` のみで、新しいピアIDが返却されるわけではありません。ピアIDは暫定的に割り当てられていたものを引き続き使用する（割り当てられていたピアIDのステータスが暫定でなくなる）という仕様になっております。

誤解が生じにくいよう、 #12 で補足を追加させていただきました！ ありがとうございます。

**Comment by ingen084** [comment]
返信ありがとうございます。
そうだったんですね！誤解しておりました。
補足ありがとうございました！
