### ISSUE TITLE
仕様として不明な点

### ISSUE THREAD

**Issue by ingen084** [p2pquake/epsp-specifications#11]
## コード551 地震情報 の署名を検証するデータの結合方法

`ピアとのデータ通信` `2.署名` にかかれている  

> 地震情報では「地震情報概要」と「地震情報詳細」

の部分ですが、~メッセージを繋げている `:` を含むのかがわかりません。~

その他の部分にも区切り文字の指定はないので `:` はなしということでよさそうですね。  
失礼しました。。。

## 署名なしで地震感知情報を発信する際の書式

署名無しで発信が可能なことは明記されていますが、発信方法の記載がありません。

## 署名の検証に失敗した際の挙動

定義がないため、そのままピアに送信してしまって問題ないのか悩みます。  
(荒らしがいるとネットワークが輻輳してしまいそうですが…。)

---

明記していただけますと幸いです。

**Comment by typewriter** [comment]
@ingen084 大変遅くなりました。ありがとうございます。

> 署名なしで地震感知情報を発信する際の書式

署名に関係する部分は空文字列として発信をお願いします。
#13 で補足を追記させていただきました！

> 署名の検証に失敗した際の挙動

こちらについては、「ピアとのデータ通信 > 1.重複判定・各ピアへの伝達」にありますように、署名検証より前に他のピアへ送信することを推奨しております。遅延を少しでも小さくすることを意図しています。

輻輳制御は現状特に規定しておらず、クライアントの実装に依存しています。

（以下仕様書より引用） _同一「ではない」と判断された場合、署名やその他を検証する前に、速やかにデータを送ってきたピア「以外」の他ピアへ情報を伝達する必要があります_

**Comment by ingen084** [comment]
返信ありがとうございます！

> 署名に関係する部分は空文字列として発信をお願いします。
> #13 で補足を追記させていただきました！

承知いたしました。  
補足の追記ありがとうございます！

>こちらについては、「ピアとのデータ通信 > 1.重複判定・各ピアへの伝達」にありますように、署名検証より前に他のピアへ送信することを推奨しております。遅延を少しでも小さくすることを意図しています。

失念しておりました。  
そのように実装させていただきます。  
ありがとうございました。
