### ISSUE TITLE
3桁の数字（コード）一覧表の232は212の間違いですか？

### ISSUE THREAD

**Issue by anatawa12** [p2pquake/epsp-specifications#8]
3桁の数字（コード）一覧表の232は

232 | （※本来は[112]に対するものですが、通信ステップの簡略化により変更しています）<br>([131]に対し)対応プロトコルバージョン、ソフトウェア名・ソフトウェアバージョンを返します。　データ：プロトコルバージョン、ソフトウェア名、バージョン
-- | :--

とありますが、[2.プロトコルバージョン等の通知](https://p2pquake.github.io/epsp-specifications/epsp-specifications.html#networkjoin-2)では212で返答するように書かれています。
また、EPSP-Peer-CSでも212として処理されています
[AbstractState.cs#L26](https://github.com/p2pquake/epsp-peer-cs/blob/master/Client/Client/State/AbstractState.cs#L26)\
[ClientConst.cs#L15](https://github.com/p2pquake/epsp-peer-cs/blob/61d88b6e56f0aa124f3192a5304f0efb16175080/Client/Client/General/ClientConst.cs#L15)

どちらが正しいのでしょうか？

**Comment by typewriter** [comment]
@anatawa12 大変遅くなりました。
正しいコードは `212` です。 #14 で修正させていただきました！ ありがとうございます。
